copyright: Copyright &copy 2023; Written & Published by <a href="https://github.com/imshakil">imShakil</a>
site_name: Shakil's Hand Notes
site_url: https://imshakil.github.io/hand-notes
site_author: Mobarak Hosen Shakil
site_description: It's my personal note pages curated from different sources. I have published, thought it will help someone in the community.
docs_dir: docs
theme: readthedocs

