copyright: Copyright &copy; 2023, Shakil's Hand Notes
repo_name: Hand Notes
repo_url: https://github.com/imshakil/hand-notes
site_name: Shakil's Hand Notes
site_author: Mobarak Hosen Shakil
site_description: Shakil's Personal Hand notes
docs_dir: ./docs/
edit_uri: edit/main/docs

nav:
  - Home: 'index.md'
  - 'Apache': 'apache/README.md'
  - 'Centos': 'apache/httpd-on-centos.md'
  - Linux: 'linux/README.md'
  - 'Commands': 'linux/top.md'
  - About: about.md
  - Contact: contact.md
  - Support: support.md
theme: readthedocs
